stages:
  load_data:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/get_data.py
    - src/data/load_data.py
    - given_data/winequality.csv
    outs:
    - data/raw/winequality.csv

  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv
#
  train_and_evaluate:
    cmd: python src/models/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv
    - src/models/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
#    metrics:
#    - reports/scores.json:
#        cache: false
#    - reports/params.json:
#        cache: false
#  log_production_model:
#    cmd: python src/models/log_production_model.py --config=params.yaml
#    deps:
#    - src/models/log_production_model.py
#    outs:
#    - saved_models/model.joblib