artifact_uri: ElasticNet Regression/0/c92363bfed564b87910fc53950a43a2e/artifacts
end_time: 1649273371592
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c92363bfed564b87910fc53950a43a2e
run_uuid: c92363bfed564b87910fc53950a43a2e
source_name: ''
source_type: 4
source_version: ''
start_time: 1649273369082
status: 4
tags: []
user_id: sanand
