artifact_uri: ElasticNetRegression/0/8333c552040b40a19faabc0ef5c77dfc/artifacts
end_time: 1649267380172
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8333c552040b40a19faabc0ef5c77dfc
run_uuid: 8333c552040b40a19faabc0ef5c77dfc
source_name: ''
source_type: 4
source_version: ''
start_time: 1649267377685
status: 4
tags: []
user_id: sanand
