artifact_uri: ElasticNet Regression/0/c62a732627a44abdaea195e7df7365f3/artifacts
end_time: 1649267016976
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c62a732627a44abdaea195e7df7365f3
run_uuid: c62a732627a44abdaea195e7df7365f3
source_name: ''
source_type: 4
source_version: ''
start_time: 1649267014388
status: 4
tags: []
user_id: sanand
